export const socialBadgeMap: Record<string, { label: string; logo: string; color: string }> = {
  Github:      { label: "GitHub",      logo: "github",      color: "181717" },
  Instagram:   { label: "Instagram",   logo: "instagram",   color: "E4405F" },
  LinkedIn:    { label: "LinkedIn",    logo: "linkedin",    color: "0077B5" },
  Medium:      { label: "Medium",      logo: "medium",      color: "12100E" },
  Twitter:     { label: "Twitter",     logo: "twitter",     color: "1DA1F2" },
  Facebook:    { label: "Facebook",    logo: "facebook",    color: "1877F2" },
  Leetcode:    { label: "LeetCode",    logo: "leetcode",    color: "FFA116" },
  Discord:     { label: "Discord",     logo: "discord",     color: "5865F2" },
  Dribble:     { label: "Dribbble",    logo: "dribbble",    color: "EA4C89" },
  YouTube:     { label: "YouTube",     logo: "youtube",     color: "FF0000" },
  "Dev.to":    { label: "DEV",         logo: "dev.to",      color: "0A0A0A" },
  Reddit:      { label: "Reddit",      logo: "reddit",      color: "FF4500" },
  Stackoverflow: { label: "Stack Overflow", logo: "stackoverflow", color: "F58025" },
  Other:       { label: "Website",     logo: "internet-explorer", color: "4285F4" },
};
